In [14]:
import torch
import gensim.downloader as api # type:ignore
model = api.load("word2vec-google-news-300")

In [15]:
word_vectors = model
print(word_vectors.most_similar('computer'))

[('computers', 0.7979379892349243), ('laptop', 0.6640493273735046), ('laptop_computer', 0.6548868417739868), ('Computer', 0.647333562374115), ('com_puter', 0.6082080006599426), ('technician_Leonard_Luchko', 0.5662748217582703), ('mainframes_minicomputers', 0.5617720484733582), ('laptop_computers', 0.5585449934005737), ('PC', 0.5539618730545044), ('maker_Dell_DELL.O', 0.5519254207611084)]


In [16]:
# Example of using most_similar
print(word_vectors.most_similar(positive=['king', 'woman'], negative=['man'], topn=10))

[('queen', 0.7118193507194519), ('monarch', 0.6189674139022827), ('princess', 0.5902431011199951), ('crown_prince', 0.5499460697174072), ('prince', 0.5377321839332581), ('kings', 0.5236844420433044), ('Queen_Consort', 0.5235945582389832), ('queens', 0.518113374710083), ('sultan', 0.5098593235015869), ('monarchy', 0.5087411403656006)]


In [17]:
# Example of calculating similarity
print(word_vectors.similarity('woman', 'man'))
print(word_vectors.similarity('king', 'queen'))
print(word_vectors.similarity('uncle', 'aunt'))
print(word_vectors.similarity('boy', 'girl'))
print(word_vectors.similarity('nephew', 'niece'))
print(word_vectors.similarity('paper', 'water'))

0.76640123
0.6510957
0.7643474
0.8543272
0.7594367
0.11408084


In [18]:
print(word_vectors.most_similar("tower", topn=5))

[('towers', 0.8531750440597534), ('skyscraper', 0.6417425870895386), ('Tower', 0.639177143573761), ('spire', 0.594687819480896), ('responded_Understood_Atlasjet', 0.5931612253189087)]


In [19]:
import numpy as np

word1 = 'man'
word2 = 'woman'


word3 = 'semiconductor'
word4 = 'earthworm'

word5 = 'nephew'
word6 = 'niece'

# calculate the vector difference
vector_difference1 = model[word1] - model[word2]
vector_difference2 = model[word3] - model[word4]
vector_difference3 = model[word5] - model[word6]

# calculate the magnitude of the vector difference
magnitude_of_difference1 = np.linalg.norm(vector_difference1)
magnitude_of_difference2 = np.linalg.norm(vector_difference2)
magnitude_of_difference3 = np.linalg.norm(vector_difference3)

# Print the magnitude of the difference
print("The magnitude of the difference between '{}' and '{}' is {:.2f}".format(word1, word2, magnitude_of_difference1))
print("The magnitude of the difference between '{}' and '{}' is {:.2f}".format(word3, word4, magnitude_of_difference2))
print("The magnitude of the difference between '{}' and '{}' is {:.2f}".format(word5, word6, magnitude_of_difference3))

The magnitude of the difference between 'man' and 'woman' is 1.73
The magnitude of the difference between 'semiconductor' and 'earthworm' is 5.67
The magnitude of the difference between 'nephew' and 'niece' is 1.96


In [20]:
input_ids = torch.tensor([2,3,5,1])

In [21]:
vocab_size = 6
output_dim = 3

torch.manual_seed(124)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(embedding_layer.weight)

Parameter containing:
tensor([[-0.5728,  0.2498, -1.2034],
        [-1.5485, -0.2655,  0.8484],
        [ 0.8453, -1.4826,  0.1986],
        [ 0.1190, -0.8403,  1.4388],
        [-0.9206,  0.1130, -0.7559],
        [-0.3033, -1.6082,  1.0092]], requires_grad=True)


In [22]:
print(embedding_layer(torch.tensor([3])))

tensor([[ 0.1190, -0.8403,  1.4388]], grad_fn=<EmbeddingBackward0>)


In [24]:
print(embedding_layer(input_ids))

tensor([[ 0.8453, -1.4826,  0.1986],
        [ 0.1190, -0.8403,  1.4388],
        [-0.3033, -1.6082,  1.0092],
        [-1.5485, -0.2655,  0.8484]], grad_fn=<EmbeddingBackward0>)


The embedding layer is simple lookup operation to look for the embedding value of a specific token.